-- Experiencia Bayer: carga inicial de ubicaciones desde Ubicaciones_Bayer.xlsx
-- Ejecutar después de 002_create_usuarios.sql y 003_create_ubicaciones.sql.
-- site_referent_user_id queda NULL hasta asignar el encargado de cada site.

-- Elimina únicamente la fila de prueba creada por 003_create_ubicaciones.sql.
delete from public.ubicaciones
where source_id = 0;

insert into public.ubicaciones (
  source_id,
  entity,
  name,
  location_type,
  main_activity,
  published_address,
  locality,
  province,
  latitude,
  longitude,
  coordinate_quality,
  google_maps_url,
  notes,
  status,
  site_referent_user_id
)
values
(
  1,
  'AgroBayer',
  'Zarate I',
  'Planta industrial',
  'Fitosanitarios: suspensiones concentradas, herbicidas y concentrados emulsionables',
  'Camino de la Costa Brava s/n, Parque Industrial Zarate',
  'Zarate',
  'Buenos Aires',
  -34.075833,
  -59.057722,
  'Exacta publicada',
  'https://www.google.com/maps/search/?api=1&query=-34.075833,-59.057722',
  'Registro oficial de plantas elaboradoras de fitosanitarios; direccion corroborada por U.I. Zarate.',
  'Actual',
  NULL
),
(
  2,
  'AgroBayer',
  'Zarate II',
  'Planta industrial',
  'Formulacion de herbicidas',
  'Ruta Provincial 6, km 83,1',
  'Zarate',
  'Buenos Aires',
  -34.101000,
  -59.018000,
  'Referencia aproximada',
  'https://www.google.com/maps/search/?api=1&query=-34.101000,-59.018000',
  'Direccion publicada por Bayer; coordenada de referencia, validar acceso y pin.',
  'Actual',
  NULL
),
(
  3,
  'AgroBayer',
  'Planta Maria Eugenia',
  'Planta industrial',
  'Procesamiento de semillas de maiz; calidad, ingenieria e investigacion de produccion',
  'Ruta Provincial 31, km 170',
  'Rojas',
  'Buenos Aires',
  -34.183000,
  -60.707000,
  'Referencia aproximada',
  'https://www.google.com/maps/search/?api=1&query=-34.183000,-60.707000',
  'Bayer confirma planta en Rojas y direccion; coordenada de referencia, validar acceso y pin.',
  'Actual',
  NULL
),
(
  4,
  'AgroBayer',
  'Estacion Experimental Fontezuela',
  'I+D / campo experimental',
  'Mejoramiento de maiz y soja; ensayos de eficacia y seguridad; fitopatologia e invernaculos',
  'Ruta Nacional 8, km 214',
  'Fontezuela / Pergamino',
  'Buenos Aires',
  -33.917000,
  -60.467000,
  'Referencia de localidad',
  'https://www.google.com/maps/search/?api=1&query=-33.917000,-60.467000',
  'Bayer informa RN 8 km 214; coordenada de Fontezuela, no del porton confirmado.',
  'Actual',
  NULL
),
(
  5,
  'AgroBayer',
  'Campus Bayer',
  'I+D / demostracion',
  'Pruebas de tecnologias, ensayos, investigaciones y capacitacion',
  'Direccion no publicada',
  'Pergamino',
  'Buenos Aires',
  -33.892800,
  -60.573600,
  'Referencia de localidad',
  'https://www.google.com/maps/search/?api=1&query=-33.892800,-60.573600',
  'Bayer lo situa en Pergamino; no se encontro direccion publica verificable.',
  'Actual',
  NULL
),
(
  6,
  'AgroBayer',
  'Estacion de innovacion Rio Cuarto',
  'I+D / campo experimental',
  'Soporte a programas de mejoramiento para la region centro',
  'Direccion no publicada',
  'Rio Cuarto',
  'Cordoba',
  -33.123200,
  -64.349300,
  'Referencia de localidad',
  'https://www.google.com/maps/search/?api=1&query=-33.123200,-64.349300',
  'Ubicacion de ciudad; falta confirmar el predio especifico.',
  'Actual',
  NULL
),
(
  7,
  'AgroBayer',
  'Breeding Tucuman',
  'I+D / mejoramiento',
  'Mejoramiento vegetal y testeo para la region norte',
  'Parque Industrial Tucuman, Av. Circunvalacion, km 1294',
  'Tucuman',
  'Tucuman',
  -26.826000,
  -65.173000,
  'Referencia aproximada',
  'https://www.google.com/maps/search/?api=1&query=-26.826000,-65.173000',
  'Direccion publicada por Bayer; coordenada de referencia, validar acceso y pin.',
  'Actual',
  NULL
),
(
  8,
  'AgroBayer',
  'Centro de produccion de vegetales',
  'Produccion de semillas',
  'Produccion de semillas de hortalizas',
  'Direccion y localidad no publicadas',
  'Mendoza',
  'Mendoza',
  -32.889500,
  -68.845800,
  'Referencia provincial',
  'https://www.google.com/maps/search/?api=1&query=-32.889500,-68.845800',
  'Bayer menciona el centro en Mendoza, sin localidad ni predio publico. Coordenada de ciudad.',
  'Actual',
  NULL
),
(
  9,
  'Bayer ForwardFarming',
  'Agricola Testa',
  'Campo demostrativo asociado',
  'Agricultura regenerativa y demostraciones',
  'Predio privado; direccion no publicada',
  'Pergamino',
  'Buenos Aires',
  -33.892800,
  -60.573600,
  'Referencia de localidad',
  'https://www.google.com/maps/search/?api=1&query=-33.892800,-60.573600',
  'No es necesariamente propiedad de Bayer; coordenada de Pergamino.',
  'Asociado',
  NULL
),
(
  10,
  'Bayer ForwardFarming',
  'Cropmix / Prodeman',
  'Campo demostrativo asociado',
  'Agricultura regenerativa; establecimiento de 318 ha',
  'Predio privado; direccion no publicada',
  'General Cabrera',
  'Cordoba',
  -32.813700,
  -63.873600,
  'Referencia de localidad',
  'https://www.google.com/maps/search/?api=1&query=-32.813700,-63.873600',
  'No es propiedad de Bayer; coordenada de General Cabrera.',
  'Asociado',
  NULL
)
on conflict (source_id) do update set
  entity = excluded.entity,
  name = excluded.name,
  location_type = excluded.location_type,
  main_activity = excluded.main_activity,
  published_address = excluded.published_address,
  locality = excluded.locality,
  province = excluded.province,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  coordinate_quality = excluded.coordinate_quality,
  google_maps_url = excluded.google_maps_url,
  notes = excluded.notes,
  status = excluded.status;

-- Verificacion rapida: debe devolver 10 filas.
select
  source_id,
  name,
  latitude,
  longitude,
  status,
  site_referent_user_id
from public.ubicaciones
order by source_id;
